# Site settings
title: Justin Dunn
email: dunnjustin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Justin Dunn's personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://justinrdunn.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  justinrdunn

# Build settings
markdown: kramdown
highlighter: rouge
